GET http://localhost:5000/api/auth

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "binhkieu",
  "password": "binhkieu"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "henry",
  "password": "henry"
}

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQ1YTM1M2Q2MThjNzc0YTQwNWMxN2MiLCJpYXQiOjE2NjU1MDgxNzl9.kq2g-gef98Xqm2nzRrTqJVtZV4XfQs_EEZ0cRx6ZrVk

{
  "title": "Grapql",
  "description": "Advanced tool to communicate with backend",
  "url": "Grapql.com",
  "status": "TO LEARN"
}

###

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQ1YTM1M2Q2MThjNzc0YTQwNWMxN2MiLCJpYXQiOjE2NjU1MDgxNzl9.kq2g-gef98Xqm2nzRrTqJVtZV4XfQs_EEZ0cRx6ZrVk
###

PUT http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQ1YTM1M2Q2MThjNzc0YTQwNWMxN2MiLCJpYXQiOjE2NjU1MDgxNzl9.kq2g-gef98Xqm2nzRrTqJVtZV4XfQs_EEZ0cRx6ZrVk
{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQ1YTM1M2Q2MThjNzc0YTQwNWMxN2MiLCJpYXQiOjE2NjU1MDgxNzl9.kq2g-gef98Xqm2nzRrTqJVtZV4XfQs_EEZ0cRx6ZrVk